/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as UsersRouteImport } from './users'
import { Route as IndexRouteImport } from './index'
import { Route as UsersIndexRouteImport } from './users/index'
import { Route as UsersInfoRouteImport } from './users/Info'
import { Route as UsersInfoDetailIdRouteImport } from './users/InfoDetail.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
})
const UsersInfoRoute = UsersInfoRouteImport.update({
  id: '/Info',
  path: '/Info',
  getParentRoute: () => UsersRoute,
})
const UsersInfoDetailIdRoute = UsersInfoDetailIdRouteImport.update({
  id: '/InfoDetail/$id',
  path: '/InfoDetail/$id',
  getParentRoute: () => UsersRoute,
})

const UsersRouteChildren = {
  UsersInfoRoute: UsersInfoRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersInfoDetailIdRoute: UsersInfoDetailIdRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
