/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as UsersRouteImport } from './pages/Users'
import { Route as IndexRouteImport } from './pages/index'
import { Route as UsersIndexRouteImport } from './pages/Users/index'
import { Route as UsersRegiRouteImport } from './pages/Users/Regi'
import { Route as UsersSysIndexRouteImport } from './pages/Users/Sys/index'
import { Route as UsersRegiIndexRouteImport } from './pages/Users/Regi/index'
import { Route as UsersAppIndexRouteImport } from './pages/Users/App/index'
import { Route as UsersRegiInfoRouteImport } from './pages/Users/Regi/Info'
import { Route as UsersRegiInfoDetailIdRouteImport } from './pages/Users/Regi/InfoDetail.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiRoute = UsersRegiRouteImport.update({
  id: '/Regi',
  path: '/Regi',
  getParentRoute: () => UsersRoute,
})
const UsersSysIndexRoute = UsersSysIndexRouteImport.update({
  id: '/Sys/',
  path: '/Sys/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiIndexRoute = UsersRegiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRegiRoute,
})
const UsersAppIndexRoute = UsersAppIndexRouteImport.update({
  id: '/App/',
  path: '/App/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiInfoRoute = UsersRegiInfoRouteImport.update({
  id: '/Info',
  path: '/Info',
  getParentRoute: () => UsersRegiRoute,
})
const UsersRegiInfoDetailIdRoute = UsersRegiInfoDetailIdRouteImport.update({
  id: '/InfoDetail/$id',
  path: '/InfoDetail/$id',
  getParentRoute: () => UsersRegiRoute,
})

const UsersRegiRouteChildren = {
  UsersRegiInfoRoute: UsersRegiInfoRoute,
  UsersRegiIndexRoute: UsersRegiIndexRoute,
  UsersRegiInfoDetailIdRoute: UsersRegiInfoDetailIdRoute,
}

const UsersRegiRouteWithChildren = UsersRegiRoute._addFileChildren(
  UsersRegiRouteChildren,
)

const UsersRouteChildren = {
  UsersRegiRoute: UsersRegiRouteWithChildren,
  UsersIndexRoute: UsersIndexRoute,
  UsersAppIndexRoute: UsersAppIndexRoute,
  UsersSysIndexRoute: UsersSysIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
