/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as UsersRouteImport } from './pages/users'
import { Route as IndexRouteImport } from './pages/index'
import { Route as UsersIndexRouteImport } from './pages/users/index'
import { Route as UsersRegiRouteImport } from './pages/users/regi'
import { Route as UsersSysIndexRouteImport } from './pages/users/sys/index'
import { Route as UsersRegiIndexRouteImport } from './pages/users/regi/index'
import { Route as UsersAppIndexRouteImport } from './pages/users/app/index'
import { Route as UsersRegiInfoRouteImport } from './pages/users/regi/info'
import { Route as UsersRegiCreateRouteImport } from './pages/users/regi/create'
import { Route as UsersRegiInfoDetailIdRouteImport } from './pages/users/regi/infoDetail.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiRoute = UsersRegiRouteImport.update({
  id: '/regi',
  path: '/regi',
  getParentRoute: () => UsersRoute,
})
const UsersSysIndexRoute = UsersSysIndexRouteImport.update({
  id: '/sys/',
  path: '/sys/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiIndexRoute = UsersRegiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRegiRoute,
})
const UsersAppIndexRoute = UsersAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => UsersRoute,
})
const UsersRegiInfoRoute = UsersRegiInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => UsersRegiRoute,
})
const UsersRegiCreateRoute = UsersRegiCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => UsersRegiRoute,
})
const UsersRegiInfoDetailIdRoute = UsersRegiInfoDetailIdRouteImport.update({
  id: '/infoDetail/$id',
  path: '/infoDetail/$id',
  getParentRoute: () => UsersRegiRoute,
})

const UsersRegiRouteChildren = {
  UsersRegiCreateRoute: UsersRegiCreateRoute,
  UsersRegiInfoRoute: UsersRegiInfoRoute,
  UsersRegiIndexRoute: UsersRegiIndexRoute,
  UsersRegiInfoDetailIdRoute: UsersRegiInfoDetailIdRoute,
}

const UsersRegiRouteWithChildren = UsersRegiRoute._addFileChildren(
  UsersRegiRouteChildren,
)

const UsersRouteChildren = {
  UsersRegiRoute: UsersRegiRouteWithChildren,
  UsersIndexRoute: UsersIndexRoute,
  UsersAppIndexRoute: UsersAppIndexRoute,
  UsersSysIndexRoute: UsersSysIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
